### ISSUE TITLE
Why fork?

### ISSUE THREAD

**Issue by onlyjob** [docker/goamz#16]
Needless forks are harmful. Couldn't you just work with [AdRoll/goamz](https://github.com/AdRoll/goamz) and submit some pull requests?

Besides did anyone bothered to briefly document "additional functionality and services" (i.e. differences from _AdRoll/goamz_)?

**Comment by BrianBland** [comment]
The main reason was for to implement [this change](https://github.com/docker/goamz/pull/1) for [docker/distribution](github.com/docker/distribution), which is not backwards-compatible at the API level but required to fix performance issues with the library. As [AdRoll/goamz](github.com/AdRoll/goamz) has no stable or semantic versioning, this would cause all users who simply `go get github.com/AdRoll/goamz` to have broken build environments. In the long run, the intent is to switch over to using [aws/aws-sdk-go](github.com/aws/aws-sdk-go) if this proves to be stable.

**Comment by onlyjob** [comment]
Thanks. _aws-sdk-go_ does semantic versioning and their last several releases were relatively stable so switching makes sense...
